services:
  - type: web
    name: prestamos-backend
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_VERSION  
        value: 8
      - key: NODE_ENV
        value: production
